trigger:
  branches:
    include:
      - main  # Trigger on push to the main branch

pool:
  name: 'Pool'  # Replace 'AzureVM' with your self-hosted agent pool name

steps:
# Step 1: Checkout the repository
- task: Checkout@1
  displayName: 'Checkout repository'

# Step 2: Set up Python environment (if necessary)
- script: |
    python --version
    pip --version
  displayName: 'Check Python installation'

# Step 3: Give execute permission to the script (in Windows, no need for chmod, but ensure it's executable)
- script: |
    icacls run_flask_api.sh /grant Everyone:F
  displayName: 'Grant execute permissions to run_flask_api.sh'

# Step 4: Run the Flask API using the shell script
- script: |
    ./run_flask_api.sh
  displayName: 'Run Flask API'
